services:
  db:
    image: postgres:17.5-bookworm
    ports:
      - 15432:5432
    volumes: 
      - type: volume
        source: pg-data
        target: /var/lib/postgres/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
volumes:
  pg-data:
